### PR TITLE
Fix read lc rv

### PR DESCRIPTION
**Pull request by boryanah**
Adding more fields to header when outputting RV/PID light cone particle subsamples

### CODE REVIEW

**Comment by boryanah** [comment]
Ah, it seems like this contains the earlier commit for the change of keys in the HOD script -- I am sorry about that!

**Comment by lgarrison** [comment]
Oh, I see! No worries, if you want to close the other PR, we can just do everything in this PR (it's all LC related).

**Comment by boryanah** [comment]
Ok, this should have both changes!

**Comment by lgarrison** [comment]
LGTM!

**Pull request merged**
