### PR TITLE
Reduce memory usage in Menv tree queries

### PR DESCRIPTION
**Pull request by lgarrison**
This PR tries to more aggressively delete and garbage collect potentially large arrays that come out of the Menv tree queries. My thought was that the `concat_to_arr` step might be doubling the memory footprint of those arrays compared to before.  I chose to encapsulate the Menv calculation in a new function, `do_Menv_from_tree`, so that all intermediate arrays go out of scope when the function returns, giving us the best chance at reclaiming that memory.

I haven't actually done any global memory profiling, so I don't know if this is the source of @boryanah's observed memory increase.  But this is just a region of the code that I was touching recently.

@SandyYuan It looks like other parts of the `prepare_slab` function might benefit from similar encapsulation, or at least more aggressive deletion once we no longer need an array.  Other opportunities would include using float32 everywhere (I can't imagine we need float64 for anything, but we're using it in a number of places), and potentially using int32 instead of int64 indices (although we'd have to be more careful about that).

Also rolled into this PR are a few non-memory related fixes that came up when I was debugging #47.

### CODE REVIEW

**Review by SandyYuan — APPROVED** [review]

**Comment by boryanah** [comment]
Looks great to me though I haven't checked whether now I can downsample the halo light cones without running out of memory. I should perhaps do that before approving the PR? Sandy, did you also run into the same issue for your test with downsampling from yesterday?

**Comment by lgarrison** [comment]
So to summarize Slack conversations, this still runs out of memory for the halo LC HOD, right? Do we have a workaround, or should we keep this PR open while we iterate?

**Comment by SandyYuan** [comment]
This version should not have memory issues. I basically imposed a cutoff mass in which halos gets their fenv computed.

**Comment by lgarrison** [comment]
Okay, sounds great. @boryanah, did you want to test this first, or are you happy for us to merge?

**Comment by boryanah** [comment]
Let me test it on huge first -- just need to submit a job for the subsampling of box and light cone.

**Comment by boryanah** [comment]
I managed to do subsampling at z ~ 0.5 for huge box and lc, though I didn't look at memory usage (I think it was under 64 GB). I think this is ready to be approved!

**Comment by lgarrison** [comment]
In the process of fixing the tests, I was having trouble telling what were reference files and what were temporary files generated by the tests, so I did a bit of reorganization.  All the reference files now live under `ref_hod`, and I tried to delete any unused reference files. I also tried to fix the file paths so you can run the tests from any directory (previously it had to be the repo root).

**Pull request merged**
