### PR TITLE
Refactor optional dependencies; Corrfunc now optional. Migrate build to pyproject.toml.

### PR DESCRIPTION
**Pull request by lgarrison**
In discussing with @boryanah whether to spin off the power spectrum module into its own package, it came up that the Corrfunc dependency is pretty heavyweight to have installed by default. Since Corrfunc doesn't distribute binary wheels, it has to build locally, which can fail if dependencies are missing. And since there are lots of abacusutils modules that don't require Corrfunc, it seems sensible to make it optional.

And since we're refactoring the dependencies, it seems like a good time to try to finish the migration from `setup.py` to `pyproject.toml`. This PR attempts to do that.

The optional dependency scheme is now:
- `abacusutils`: most core functionality, except "hard to install" packages like Corrfunc and classy
- `abacusutils[all]`: all the core functionality, plus dependencies required by various scripts in the repo
- `abacusutils[test]`: everything in `[all]`, plus `pytest`
- `abacusutils[docs]`: for building the docs

@boryanah, @SandyYuan: please let me know if you think this makes sense. Most users will only ever use `pip install abacusutils` or `pip install abacusutils[all]`, which hopefully is easy enough to document, but obviously it's a little unfortunate to not install all packages by default.

### CODE REVIEW

**Comment by lgarrison** [comment]
Also need to update the ReadTheDocs if we adopt this PR.

**Comment by boryanah** [comment]
That looks great to me! I think this  is a good solution and having too many separate install instructions (e.g., one for power spectra, one for ZCV, one for HOD's) does not make a lot of sense and makes it difficult for the user. Perhaps if we end up adding a lot of heavier modules to the [all] version we might think again about whether adding separate installation paths for those is needed, but I think right now we are good.

**Comment by lgarrison** [comment]
@SandyYuan Corrfunc is mostly used by the HOD module, so I wanted to make sure you were aware of/okay with this change.

**Comment by lgarrison** [comment]
@SandyYuan I'm going to merge this now to fix an issue an another PR, but we can discuss this scheme further if needed.

**Pull request merged**
