### PR TITLE
Preparing for v1.4

### PR DESCRIPTION
**Pull request by lgarrison**
@boryanah @SandyYuan I think we are just about ready to make a pip release. Is there anything else either of you wanted to put in?

We can call this version 1.4. We've added a lot so we could consider bumping to 2.0, but usually that would be done to indicate we broke compatibility with earlier releases, which I don't think we've done (but let me know if you think we have).

Can you check `CHANGES.rst` to make sure it's up to date? The full set of changes is here, although it's a very big diff: https://github.com/abacusorg/abacusutils/compare/v1.3.0...main. It's probably best to just read through the changelog and look at closed PRs to see if we missed any big items.

One outstanding issue that may break future releases is that we'll want to unify the TSC and CIC interfaces. But it's probably not worth holding up this release to fix that.

### CODE REVIEW

**Comment by lgarrison** [comment]
Looks like classy compilation is broken now that Cython 3.0 has been released on pip (https://github.com/lesgourg/class_public/issues/531). We can fix it in CI, but there's not much we can do for end users. But classy is hidden behind `abacusutils[all]`, so at least it won't bother everyone.

**Comment by boryanah** [comment]
I would like to add in my changes from the power_spec branch (I haven't pushed to it yet but will do so tomorrow) -- is it possible to "include" it as part of this PR and version release?

**Comment by lgarrison** [comment]
Yeah, the release doesn't need to come from this PR. You can just make another PR into main. I was mostly just using this PR to fix up the changelog (and fix the classy build apparently) and asking for any last contributions.

**Comment by boryanah** [comment]
Ah, I see -- looks good to me!

**Comment by lgarrison** [comment]
@boryanah I'm going to merge this just to get the CI passing again, but let me know when you've pushed your `power_spec` changes.

**Comment by boryanah** [comment]
Great -- started a new PR for CV power spectrum

**Pull request merged**
